name: Snake Animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ileriayo/github-contribution-grid-snake-action@v1
        with:
          github_user_name: rigelshaw
          output_file: github-contribution-grid-snake-dark.svg
